name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: $version
authors: [nisovin, TheComputerGeek2, Chronoken, tonythemacaroni, JasperLorelai]
api-version: "1.19"
softdepend:
    - GriefPrevention
    - Vault
    - ProtocolLib
    - WorldGuard
    - Residence
    - PowerNBT
    - LibsDisguises
    - NoCheatPlus
    - PlaceholderAPI
    - Citizens
